// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview Generates a set of visualizations tailored to the dataset, along with AI-generated descriptions explaining the key insights revealed by each visualization.
 *
 * - generateVisualizations - A function that handles the visualization generation process.
 * - GenerateVisualizationsInput - The input type for the generateVisualizations function.
 * - GenerateVisualizationsOutput - The return type for the generateVisualizations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateVisualizationsInputSchema = z.object({
  datasetDescription: z
    .string()
    .describe('A detailed description of the dataset, including its columns and purpose.'),
  datasetSample: z
    .string()
    .describe('A sample of the dataset in CSV format.'),
});
export type GenerateVisualizationsInput = z.infer<typeof GenerateVisualizationsInputSchema>;

const VisualizationSchema = z.object({
  visualizationType: z.string().describe('The type of the visualization (e.g., scatter plot, histogram, bar chart).'),
  description: z.string().describe('A textual description of the visualization and its key insights.'),
  imageDataUri: z.string().describe('The visualization as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'),
});

const GenerateVisualizationsOutputSchema = z.array(VisualizationSchema);
export type GenerateVisualizationsOutput = z.infer<typeof GenerateVisualizationsOutputSchema>;

export async function generateVisualizations(input: GenerateVisualizationsInput): Promise<GenerateVisualizationsOutput> {
  return generateVisualizationsFlow(input);
}

const visualizationPrompt = ai.definePrompt({
  name: 'visualizationPrompt',
  input: {schema: GenerateVisualizationsInputSchema},
  output: {schema: GenerateVisualizationsOutputSchema},
  prompt: `You are an expert data analyst. You will generate a set of visualizations tailored to the dataset, along with AI-generated descriptions explaining the key insights revealed by each visualization.

Dataset Description: {{{datasetDescription}}}
Dataset Sample: {{{datasetSample}}}

Generate visualizations that are informative and insightful. For each visualization, provide a concise description of the visualization type and the key insights it reveals. Return the visualizations as data URIs.

{{#each this}}
Visualization Type: {{visualizationType}}
Description: {{description}}
Image Data URI: {{media url=imageDataUri}}
{{/each}}`,
});

const generateVisualizationsFlow = ai.defineFlow(
  {
    name: 'generateVisualizationsFlow',
    inputSchema: GenerateVisualizationsInputSchema,
    outputSchema: GenerateVisualizationsOutputSchema,
  },
  async input => {
    // TODO: Implement the logic to generate visualizations and their descriptions.
    // This is a placeholder implementation.
    const exampleVisualization = {
      visualizationType: 'Scatter Plot',
      description: 'A scatter plot showing the relationship between two variables in the dataset.',
      imageDataUri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w+r8jUAAAP4E0ocw9LX0AAAAAElFTkSuQmCC', // Placeholder image
    };
    const {output} = await visualizationPrompt(input);    
    return [exampleVisualization, exampleVisualization];
  }
);
